modLoader="javafml"
loaderVersion="[41,)"
license="MIT"

[[mods]]
modId="betterfurnacesreforged"
version="${version}"
displayName="BetterFurnaces Reforged"
credits=" TheFrogMC(Original mod creator) and Qelifern (Iron Furnaces creator)"
displayURL="https://www.curseforge.com/minecraft/mc-mods/better-furnaces-reforged/"
logoFile="bfr_icon.png"
authors="Wilyicaro"
description='''
This mod is a remake of the outdated mod from 1.7.10, Better Furnaces, presenting the concept used in the original mod
'''

[[dependencies.betterfurnacesreforged]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"
[[dependencies.betterfurnacesreforged]]
modId="factory_api"
mandatory=true
versionRange="[0.1.6,]"
ordering="NONE"
side="BOTH"
[[dependencies.betterfurnacesreforged]]
modId="pmmo"
mandatory=false
versionRange="[1.19.4-,)"
ordering="NONE"
side="BOTH"
[[dependencies.betterfurnacesreforged]]
   modId="jei"
   mandatory=false
   versionRange="[8,)"
   ordering="NONE"
   side="BOTH"
[[dependencies.betterfurnacesreforged]]
   modId="ftbguilibrary"
   mandatory=false
   versionRange="[1,)"
   ordering="NONE"
   side="BOTH"




